/*
*     COPYRIGHT NOTICE
*     Copyright(c) 2017~2019, Team Shanghai Dream Equinox
*     All rights reserved.
*
* @file		defineMain.h
* @brief	This Program is LiveProject Project.
* @author	alopex
* @version	v1.00a
* @date		2019-01-20
*/
#pragma once

#ifndef __DEFINEMAIN_H_
#define __DEFINEMAIN_H_

// Definitions
#pragma warning (disable:4996)

#define WM_USER_MESSAGE_MENU					(WM_USER + 1)
#define WM_USER_MESSAGE_WALLVIDEO_RESTART		(WM_USER + 2)

#define WM_USER_MESSAGE_WALLVIDEO_INSERT		(WM_USER + 10)
#define WM_USER_MESSAGE_WALLVIDEO_DELETE		(WM_USER + 11)
#define WM_USER_MESSAGE_WALLVIDEO_SEARCH		(WM_USER + 12)
#define WM_USER_MESSAGE_WALLVIDEO_ADDITEM		(WM_USER + 13)
#define WM_USER_MESSAGE_WALLVIDEO_ADDSHOT		(WM_USER + 14)
#define WM_USER_MESSAGE_WALLGRAPH_INSERT		(WM_USER + 15)
#define WM_USER_MESSAGE_WALLGRAPH_DELETE		(WM_USER + 16)
#define WM_USER_MESSAGE_WALLGRAPH_SEARCH		(WM_USER + 17)
#define WM_USER_MESSAGE_WALLGRAPH_ADDITEM		(WM_USER + 18)
#define	WM_USER_MESSAGE_WALLGRAPH_ADDSHOT		(WM_USER + 19)

#define WM_USER_MESSAGE_SETTINGHOME_SEARCH		(WM_USER + 20)
#define WM_USER_MESSAGE_SETTINGWALL_SEARCH		(WM_USER + 21)
#define WM_USER_MESSAGE_SETTINGVIDEO_SEARCH		(WM_USER + 22)
#define WM_USER_MESSAGE_SETTINGAUDIO_SEARCH		(WM_USER + 23)
#define WM_USER_MESSAGE_SETTINGALBUM_SEARCH		(WM_USER + 24)
#define WM_USER_MESSAGE_SETTINGSHOT_SEARCH		(WM_USER + 25)
#define WM_USER_MESSAGE_SETTINGAI_SEARCH		(WM_USER + 26)
#define WM_USER_MESSAGE_SETTINGWALL_GETCONFIG	(WM_USER + 27)
#define WM_USER_MESSAGE_SETTINGWALL_SETCONFIG	(WM_USER + 28)


#endif // !__DEFINEMAIN_H_

